name: GitHub CI

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 0

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  test:
    name: 1.19.3-buster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        run: "git clone --depth 1 https://github.com/docker-library/official-images.git -b master ~/oi\necho BASHBREW_BUILDKIT_SYNTAX=\"$(< ~/oi/.bashbrew-buildkit-syntax)\" >> \"$GITHUB_ENV\"\n{ echo FROM busybox:latest; echo RUN :; } | docker build --no-cache --tag image-list-marker -"
      - name: Pull Dependencies
        run: "docker pull buildpack-deps:buster-scm"
      - name: Build 1.19.3-buster
        run: "DOCKER_BUILDKIT=0 docker build --tag golang:1.19.3-buster --tag golang:1.19-buster --tag golang:1-buster --tag golang:buster  -f ./golang/1.19/buster/Dockerfile ."
      - name: History 1.19.3-buster
        run: "docker history golang:1.19.3-buster"
      - name: Test 1.19.3-buster
        run: "set -- golang:1.19.3-buster\nif [ -s ./.test/config.sh ]; then set -- --config ~/oi/test/config.sh --config ./.test/config.sh \"$@\"; fi\n~/oi/test/run.sh \"$@\""
      - name: '"docker images"'
        run: "docker image ls --filter since=image-list-marker"
