name: GitHub CI

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 0

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  generate-jobs:
    name: Generate Jobs
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        include:
          -
            name: golang-1.19.3-bullseye
            os: "ubuntu-latest"
            meta:
                entries:
                  -
                    name: golang-1.19.3-bullseye
                    tags:
                      - golang:1.19.3-bullseye
                    file: golang/1.19/bullseye/Dockfile
                    froms:
                      - "buildpack-deps:bullseye-scm"
                froms:
                  -
                    "buildpack-deps:bullseye-scm"
                image: dongjiang1989/bullseye
  test:
    needs: generate-jobs
    strategy: ${{ fromJson(needs.generate-jobs.strategy) }}
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ${{ matrix.meta.entries.file }}
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: ${{ matrix.meta.entries.tags }}
          cache-from: type=registry,ref=${{ matrix.meta.image }}:master
          cache-to: type=inline
      - name: Test 1.19.3-buster
        run: |
          docker pull ${{ matrix.meta.image}}:${{ matrix.meta.entries.tags }}
          docker image inspect ${{ matrix.meta.image}}:${{ matrix.meta.entries.tags }}
